### ISSUE TITLE
Alternative Ruby Mine Licenses?

### ISSUE THREAD

**Issue by x0lexicality0x** [railsbridge/docs#402]
Hi there!

This might be too late for this weekend's workshop, but has Rails Bridge considered getting a special license from RubyMine?  It looks like one of these options might allow workshop attendees to get a free license to a quality software at no cost to anyone. I might be wrong, but it seems like something worth looking in to.

Here's the link: <https://www.jetbrains.com/ruby/buy/license-matrix.jsp>

Best,

Alex

**Comment by lilliealbert** [comment]
That's an interesting idea, @x0lexicality0x, but I'm not sure that we have the bandwidth to get the license and then keep track of distributing licenses to students. At the moment, we're looking into recommending Atom instead of Sublime since Atom is actually free and seems to have the same features.

RubyMine is awesome, but I don't think that RailsBridge workshops require quite that much IDE-power. I say all of this as an avid RubyMine fan, btw :smile:
