### ISSUE TITLE
Warning: Insecure world writable dir /usr/local in PATH, mode 040777

### ISSUE THREAD

**Issue by leferraz** [railsbridge/docs#405]
Hello,
I'm following this tutorial [http://installfest.railsbridge.org/installfest/create_a_rails_app] and have been getting a couple of warning messages when I initialise the rails server from within the test_app directory.

Below is what I see:

Leandros-MBP-2:test_app LeandroFerraz$ rails s
/Users/LeandroFerraz/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/LeandroFerraz/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /usr/local in PATH, mode 040777
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-01-04 15:18:43] INFO  WEBrick 1.3.1
[2015-01-04 15:18:43] INFO  ruby 2.2.0 (2014-12-25) [x86_64-darwin14]
[2015-01-04 15:18:43] INFO  WEBrick::HTTPServer#start: pid=46286 port=3000

I'm not sure how to solve this issue and I can't find anything specifically as it appears above.
Could you help?

Thanks
Leo

**Comment by tjgrathwell** [comment]
The warning means the permissions are incorrectly set on your `/usr/local` directory. It could've been caused by any number of things.

The usual answer is to fix the permissions by running something like this in the command line:
`chmod -R o-w /usr/local/`

Here's an example of a Stackoverflow article on this topic: http://stackoverflow.com/questions/16899255/error-when-starting-rails-server-warning-insecure-world-writable-dir-usr-in-p
