### ISSUE TITLE
Broken Link to Ruby Forge

### ISSUE THREAD

**Issue by Faline10** [railsbridge/docs#408]
This link (http://rubyosx.rubyforge.org/) under Step 3 of OS X Panther (http://docs.railsbridge.org/installfest/osx_panther) does not work.

**Comment by tjgrathwell** [comment]
Thanks for pointing this out, @Faline10. For now, I've removed the OSX Panther setup instructions page because I'm not confident the instructions still work. I'm also not sure we get a high enough volume of attendees at RailsBridge workshops who are using that old of an OSX version.

Were you trying to use those instructions to set up Rails on your machine? What OS are you using?
