### ISSUE TITLE
p job should be p job_params

### ISSUE THREAD

**Issue by SamSinger** [railsbridge/docs#411]
def create
  p "In the create method!!!!!!"
  job = Job.create(job_params)
  p job
  redirect_to jobs_path
end

The Effective debugging tips on this page:
 http://docs.railsbridge.org/job-board/make_the_form_work?back=add_a_new_job_form

**Comment by lilliealbert** [comment]
Hi @SamSinger, I'm not sure that I see the issue here. The bullet point prior to the code block says: 

> Now, it'll will print to the console the line "In the create method!!!!" and whatever is being returned from `Job.create(job_params)`

Which to me indicates pretty clearly that `p job` was what has intended. 

"it'll will" is definitly a typo we should fix, but I'm not sure why we should be logging the job_params over the object that we made. (I'm totally happy to consider that the params would be a more helpful output, I just don't see it from what you've said here.)

**Comment by SamSinger** [comment]
Hi Lillie,
Sorry, but I didn't make the issue clear.
This code:  redirect_to jobs_path(job)
Should be: redirect_to job_path(job)
jobs_path should be singular, job_path
Right?
I'm newbie.
--Sam

On Tue, Jan 27, 2015 at 11:18 PM, Lillie Chilen <notifications@github.com>
wrote:

> Hi @SamSinger <https://github.com/SamSinger>, I'm not sure that I see the
> issue here. The bullet point prior to the code block says:
>
> Now, it'll will print to the console the line "In the create method!!!!"
> and whatever is being returned from Job.create(job_params)
>
> Which to me indicates pretty clearly that p job was what has intended.
>
> "it'll will" is definitly a typo we should fix, but I'm not sure why we
> should be logging the job_params over the object that we made. (I'm totally
> happy to consider that the params would be a more helpful output, I just
> don't see it from what you've said here.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/docs/issues/411#issuecomment-71782544>.
>



-- 
Sam Singer

**Comment by tjgrathwell** [comment]
Hey @SamSinger,

I don't think `redirect_to job_path(job)` would work at that stage of the `job-board` app, because there is nothing at that route. `jobs_path`, however, does exist (though it is blank in that stage of the curriculum).

It isn't until [the last page of the curriculum](http://docs.railsbridge.org/job-board/add_more_things) that the student is directed to create a show page for jobs.

Though the controllers and views created by `rails generate scaffold` produce a `create` action that redirects to a job show page, we're not necessarily sticking to that format in the `job-board` app.

**Comment by SamSinger** [comment]
Thanks for the explanation Travis. It makes sense to me now.
Sam

On Tuesday, April 28, 2015, Travis Grathwell <notifications@github.com>
wrote:

> Hey @SamSinger <https://github.com/SamSinger>,
>
> I don't think redirect_to job_path(job) would work at that stage of the
> job-board app, because there is nothing at that route. jobs_path,
> however, does exist (though it is blank in that stage of the curriculum).
>
> It isn't until the last page of the curriculum
> <http://docs.railsbridge.org/job-board/add_more_things> that the student
> is directed to create a show page for jobs.
>
> Though the controllers and views created by rails generate scaffold
> produce a create action that redirects to a job show page, we're not
> necessarily sticking to that format in the job-board app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/docs/issues/411#issuecomment-97288921>.
>


-- 
Sam Singer
