### ISSUE TITLE
bundle install --without production fails

### ISSUE THREAD

**Issue by jaedco** [railsbridge/docs#413]
When I type 
     bundle install --without production 
I get the following error: 
     There was an error in your Gemfile, and Bundler cannot continue.

If this fails, get a volunteer to help you edit config/environments/production.rb

**Comment by lilliealbert** [comment]
Hi @jaedco, that means that there is probably a typo in your Gemfile. Can you review and look for a typo to fix?

**Comment by jarinudom** [comment]
I'm curious as to why `--without production` is required? I fully admit I have not looked at the code yet.

**Comment by tjgrathwell** [comment]
@jarinudom [The docs](http://docs.railsbridge.org/installfest/deploy_a_rails_app) tell students to add `gem 'pg'` to their `Gemfile` in the production group for deploying to Heroku, but installing `pg` only works when you have a valid install of postgres.

Since we want to get students up and running as quickly as possible, `--without production` is quicker than adding in the extra steps for installing postgres.

**Comment by jarinudom** [comment]
Oh right yeah I remember struggling with that haha

**Comment by lilliealbert** [comment]
Hi @jaedco, we're trying out using CodeNewbie's message board for troubleshooting when students are going through the curriculum on their own. I'm going to close out this issue (since it's not really an issue with the docs, as far as we know) — if you're still having issues could you bring it up there?

http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594
