### ISSUE TITLE
Recommend atom.io instead of sublime text

### ISSUE THREAD

**Issue by EduardoBautista** [railsbridge/docs#437]
I think it might be a good idea to recommend atom.io instead of sublime text because atom appears to be more actively developed and it is open source.  It would also help with avoiding with the "buy this software now!" message that sublime will throw at users.

**Comment by lilliealbert** [comment]
That seems pretty reasonable to me; I think that Sublime was the best option at the time that we started recommending it, but it sounds like Atom has similar functionality and is actually free.

Assuming the GitHubbers will be quite partisan, but let's ask a couple for their takes anyway. :stuck_out_tongue_winking_eye: Paging @rachelmyers @eanakashima 

And some non-GitHubbers, too: @sarahmei @tjgrathwell @nfiniteset

I don't think we need a quorum of The Entire RailsBridge Community to make this change (switching from Komodo Edit to Sublime Text was a loooong discussion), but it'd be nice to get couple of opinions on it. :dancer:

**Comment by tjgrathwell** [comment]
I had some reservations about using Atom when I believed that its java-scripty nature meant I had to use it in a browser tab or something. But it's just a Sublime-influenced editor that, as far as I can tell, does everything Sublime does.

It's still probably not something that most volunteers have installed or used, but I think the differences between Atom and Sublime are minor enough that everyone can hopefully get used to it.

Unless there's some FATAL FLAW I don't know about?

**Comment by eanakashima** [comment]
:+1: Performance for really big files isn't great, but other than that I'm not sure there are any FATAL FLAWs.

Also some semi-relevant historical discussion in https://github.com/railsbridge/docs/pull/361.

**Comment by rachelmyers** [comment]
I think Atom's a great editor, and I'm on board for recommending it. There are *some* learning curves; a lot of normal editor functionality (like opening the tree view, for example) relies on keyboard shortcuts rather than having a button into the UI. Let's do this, but be prepared to help people find their way around. :deciduous_tree:

**Comment by adriarichards** [comment]
GitHub's Atom editor collects usage data, including file names that are
opened in it and sends this data back, with some of it passing through
Google Analytics.

https://atom.io/faq

https://github.com/atom/metrics

https://github.com/atom/atom/issues/4966

I tried it when it was released but after finding out about it collecting
so much data, I went back to Sublime.

Since RailsBridge is focused on getting more women into programming and
there has been ongoing harassment of women's github repos (
http://geekfeminism.wikia.com/wiki/Feminist_Software_Foundation), I'd
suggest having the docs stick with recommending an editor, like Sublime or
Textmate, that don't do this.

Also considering that Julie Ann Horvath left GitHub last year, that is
problematic in the sense that there was a cultural problem in supporting
women engineers; not by everyone who worked there but some.

Buying software licenses for a text editor is like paying for your driver's
permit; once you get the hang of it, you can go for your full driver's
license.

If $50 is a problem for students, past grumbling about it, I suggest a
special fund be setup that women can apply to within 60 days of taking a
Railsbridge where they write an essay, half a page, on how getting their
text editor paid for would improve their lives as developers.

As someone who attended my first RailsBridge in May 2010, I would
have appreciated discussions like this.



On Thursday, February 19, 2015, Rachel Myers <notifications@github.com>
wrote:

> I think Atom's a great editor, and I'm on board for recommending it. There
> are *some* learning curves; a lot of normal editor functionality (like
> opening the tree view, for example) relies on keyboard shortcuts rather
> than having a button into the UI. Let's do this, but be prepared to help
> people find their way around. [image: :deciduous_tree:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/docs/issues/437#issuecomment-75138561>.
>


-- 
Thanks,
Adria

**Comment by EduardoBautista** [comment]
> Since RailsBridge is focused on getting more women into programming and
there has been ongoing harassment of women's github repos (
http://geekfeminism.wikia.com/wiki/Feminist_Software_Foundation), I'd
suggest having the docs stick with recommending an editor, like Sublime or
Textmate, that don't do this.

>Also considering that Julie Ann Horvath left GitHub last year, that is
problematic in the sense that there was a cultural problem in supporting
women engineers; not by everyone who worked there but some.

I fail to see how Atom.io has anything to do with this.

**Comment by EduardoBautista** [comment]
I can create a PR with all the changes if you guys are busy.

**Comment by alexch** [comment]
Adria's concerns about tracking and anonymity are important. From 5 minutes' research through those links she posted, it seems that:

1. File names and paths are not tracked (there's some ambiguous language around "item names" so this needs verification)
2. It's easy to disable tracking altogether (verification needed here too of course)

Not that I'm vouching for it -- I personally have had nothing but trouble from Atom, like crashes and CPU burn and weird UI choices -- but it looks like the tracking thing may not be a deal breaker. 

Also, what's up with getting workshoppers educational licenses to RubyMine?

**Comment by adriarichards** [comment]
Privacy, identity and aggregation of behavioral data are part of high
profile discussions occurring within tech, the government (aka Snowden),
Infosec, cloud providers and the healthcare space.

As Alex said, Atom may or may not collect specific file name information.
When I reviewed it a year ago, I took screenshots and see that two things
have been added to the metrics page since then
https://github.com/atom/metrics

- Exception messages (without paths)
- Commands run (save core commands)

Screenshot of metrics page 2/26/14
https://www.evernote.com/shard/s2/sh/4fc77900-7e73-41fb-b717-f886edd6e03c/ea1fef86238245f1b303fbf0a5c9b79e/deep/0/Evernote.png

By Github being able to identifying the computer being used plus exception
messages and executed commands is intrusive and Google was cited for
similar issues with their data gathering for Google Earth a few years ago:

http://www.pcworld.com/article/2048541/google-loses-appeal-in-street-view-privacy-lawsuit.html

http://www.huffingtonpost.com/2012/04/30/google-street-view-wifi_n_1464047.html

Excerpt:
-----------------------
Between 2007 and 2010, Google equipped its Street View cars with Wi-Fi
antennas and software that collected data transmitted by Wi-Fi networks in
nearby homes and businesses, the judge observed in the opinion.

Besides collecting the network’s name called the SSID, the unique number or
the MAC address assigned to the router transmitting the wireless signal,
the signal strength, and whether the network was encrypted, to provide
enhanced location-based services, Google’s Street View cars gathered and
stored payload data that was sent and received over unencrypted Wi-Fi
connections while driving by. This could include information such as
personal emails, user names, passwords, videos and documents.
-----------------------

Returning back to the issue, I don't support data collection from a text
editor for new people joining the development community unless they opt-in,
especially due to the ongoing targeting and harassment of women occurring
in the tech space. As the bug report suggested, it would be preferred if
this data collection was disabled by default.

Specifically to Github, and in addition to Julie Ann Horvaths' experience,
Zed Shaw wrote about a problem he had with someone harassing him on github
and alleges that Github employees participated (NSFW due to swearing)
https://web.archive.org/web/20130117043748/http://sheddingbikes.com/posts/1306816425.html

I attend DEFCON on a yearly basis, monitor computer security related news
and have worked on several projects PCI-compliance projects.

That's why the Atom editor is of concern in terms of becoming the
recommended editor for Railsbridge participants who are most likely new to
development, security and privacy issues.

**Comment by lilliealbert** [comment]
@adriarichards I agree that GitHub has screwed up royally at various points in its history, and don't presume to know if they've improved post-Julie's departure, but I don't think that should be a blocker to recommending the best tool to RailsBridge attendees. We use lots of GitHub's tools to make RailsBridge happen, and I don't think Atom needs to be an exception.

Since we give very detailed instructions for installing software throughout the Installfest, I think the tracking issue could be solved by including instructions for turning it off.

**Comment by adriarichards** [comment]
Lillie,

Glad you agree that evaluating software and ensuring it meets the needs of
RailsBridge attendees is important.

**Comment by ultrasaurus** [comment]
From an editing code perspective, I think Atom is a fine choice.  I've been using it for my Node.js work, and it sounds like others have used it for Ruby with positive outcome.

chiming in on the security - privacy awareness front, I agree with @adriarichards that we have a responsibility to our students to make them aware of the implications of the software they install.  We had a lot of discussions around opt-in in doing surveys around use of Heroku's service -- which we never fully executed, but we talked about allowing people to opt-in to a follow-up survey based on their heroku usage.

I do feel like it is a strange thing in our industry today that webapps routinely track everything and desktop apps don't -- simply based on their different architecture.  The difference, of course, is that desktop apps can find and report a lot more information than web apps.  If I'm reading the issue correctly, atom is reporting information comparable to what it might do as a web app.  It would be important for @adriarichards or someone to confirm that.

**Comment by ultrasaurus** [comment]
Also, in any case, I like @lilliealbert suggestion: "Since we give very detailed instructions for installing software throughout the Installfest, I think the tracking issue could be solved by including instructions for turning it off."

**Comment by stujo** [comment]
what an excellent discussion, kudos to all of you for the wonderful contribution you are making to the tech community

**Comment by jlord** [comment]
:wave: Hiya! I'm on the Atom team at GitHub and wanted to offer up any help I can. 

Re: metrics, we gather metrics to help make Atom better by finding issues affecting many people, like [here](https://github.com/AtomLinter/Linter/issues/445). It is anonymous; we can't identify your computer or paths. Users can absolutely turn it off if they'd like. 

It'd be great to have Atom used at Railsbridge—I'm of course a bit biased, but—I think having an editor that you can hack yourself with a little css/html/js is awesome for beginners.

**Comment by mikedao** [comment]
Just wanted to offer a possible suggestion - provide instructions for both, and let people install whichever?

**Comment by mence** [comment]
I realise this thread is pretty old now but Sublime is back in active development, at least for [Sublime 3](https://www.sublimetext.com/3dev).

I think when the issue was first created, there had been a pretty big hiatus between dev builds. I guess there might be a concern that Sublime 2 was dropping behind relative to [Atom](https://atom.io/), and whether we'd want to suggest installing beta software?

**Comment by dorkrawk** [comment]
Sorry to revisit an old issue but I just came in to suggest this very same issue. I think now that Atom is post 1.0, it's worth considering updating the recommendation int the Install Fest docs.

Also, I think being able to open up folders from the command line with `atom .` without any additional setup is a nice win for acclimating students to working from the command line quickly.

**Comment by wassimk** [comment]
I think we should re-visit this and replace Sublime with Atom. It's a paid product. I know people just ignore the splash screen and never pay. Providing a free workshop but recommending paid products is a contradiction we should remove as well. I tell all my students to install Atom instead and many trip up when they see Sublime in the instructions. 

Also, Atom now lets you disable tracking. It also prompts the first time instead of just enabling by default. Changing the preference is in the easy to find core preferences menu.

Read more at:
http://blog.atom.io/2016/10/11/atom-1-11.html.

If we build the PR will it get approved?

**Comment by lilliealbert** [comment]
I'd be fine with it. Not sure how much consensus we need for this kinda thing, but I thinking getting a +1 from a few maintainers would be enough.

**Comment by rachelmyers** [comment]
I'm +1 on this. One of the initial problems with doing this was the under-the-hood metrics collection that Atom does, and that's now been made transparent and optional.

**Comment by lilliealbert** [comment]
@wassimk Wanna put together a PR?

**Comment by wassimk** [comment]
Yes, I will do this @lilliealbert.

**Comment by wassimk** [comment]
I just pushed an update in #594.

**Comment by R2D2-12** [comment]
I agree with atom.io - at project codex we were introduced to the editor and the plugins are quite easy to install and implement. Have been using it ever since.

**Comment by lilliealbert** [comment]
Merged!
