### ISSUE TITLE
Railsbridge install fest error

### ISSUE THREAD

**Issue by clickspiker23** [railsbridge/docs#467]
I was going through the railsbridge install fest and when i got to the create a rails app i ran into an issue. i successfully create the directory railsbridge and then test_app and then cd into test_app. but when im inside test_app and type rails server, i get a list of 694 errors along with some other info i dont understand.  i included the last three things from the error list.  where it  is says "my name" it is actually my full name i just took it out when i posted here

692 /Users/myname/.rvm/gems/ruby-2.2.1@global/gems/railties-4.2.1/lib/rails/application/configuration.rb
693 /Users/myname/.rvm/gems/ruby-2.2.1@global/gems/sprockets-rails-2.3.0/lib/sprockets/railtie.rb
694 /Users/myname/.rvm/gems/ruby-2.2.1@global/gems/railties-4.2.1/lib/rails/all.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

zsh: abort rails server

**Comment by tjgrathwell** [comment]
Hey @clickspiker23, this issues area is to document problems in the RailsBridge curriculum itself, rather than support people who are using it. You should totally ask your question on this Code Newbie thread, and a RailsBridge volunteer will help you work through it: http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594/4
