### ISSUE TITLE
Problem with RailsInstaller in windows XP

### ISSUE THREAD

**Issue by ZedakiJones** [railsbridge/docs#469]
The RailsInstaller doesn't seem to work properly as v2.1 it seems to expect a 64 bit OS and/or machine. I have only a 32 bit machine and Win XP. How do I get RailsBridge to work? (No I can't afford a new laptop)

**Comment by mikedao** [comment]
Unfortunately, there's not much Railsbridge can do to get Railsinstaller to work on an XP machine. 

You can submit an issue for Railsinstaller here:  https://github.com/railsinstaller/railsinstaller-windows/issues

Alternatively, perhaps you can try http://nitrous.io. It will work with browsers that support websockets, more information on that here:  http://help.nitrous.io/faq-browser-support/

**Comment by colinrubbert** [comment]
Depending on your current hardware (CPU, RAM, etc) you could potential install VirtualBox, then install linux (I'd suggest Ubuntu because of the ease of install and wide support), and after that install a Ruby/Rails environment. It's going to be hard pressed to find a lot of supported software for XP machines now that support has been officially killed for well over a year. On top of that it would be beneficial in the long run and even in the short term to use a Unix based system for software/web development. 

Nitrous.io is also a good idea as @mikedao suggested, alternatively you could use Cloud9 https://c9.io/ if you have issues with Nitrous, I know they've changed around their free/paid pricing structure lately.
