### ISSUE TITLE
Suggest RailsInstaller for OS X 10.6 - 10.8

### ISSUE THREAD

**Issue by mxhold** [railsbridge/docs#472]
During previous Installfests, we found that getting and installing Xcode can be a big pain on versions prior to Mavericks/10.9 (which only requires running `xcode-select` for gcc). Currently, [RailsInstaller](http://railsinstaller.org/) supports 10.6, 10.7, and 10.8 and is a much faster route to getting everything installed.

I'd be happy to make a PR to change the Installfest instructions for OS X 10.6, 10.7, and 10.8 to suggest just using RailsInstaller if this sounds like something you'd support changing (just wanted to check first).

**Comment by alexch** [comment]
:+1:

**Comment by tjgrathwell** [comment]
The instructions actually were set up like that until November of last year, when we removed it via this commit: https://github.com/railsbridge/docs/commit/fcd2dd6ec959794cbba09f92e13467ebeb55e6bc from https://github.com/railsbridge/docs/pull/397 with much more discussion in https://github.com/railsbridge/docs/pull/396

In summary:
* Some sort of permission problems seen when using RailsInstaller
* RailsInstaller is "pretty out of date" (the RailsInstaller page claims the OSX variant is still installing 1.9.3, which is a big downgrade from the modern 2.2)
* Students should be comfortable using the command line

In addition to that, I would add that since RailsInstaller doesn't work on Mavericks or later, we might be setting students up for failure if they use RailsInstaller now and upgrade their OS later. I'm not quite sure how well RVM/rbenv behave when confronted with a system that already has a ruby from RailsInstaller.

**Comment by alexch** [comment]
:-1: :-(​

**Comment by mxhold** [comment]
Ah I thought I remembered seeing it in the past. Ok all that sounds reasonable and I don't see any reason to change it back. Thanks for clearing that up! :smile:
