### ISSUE TITLE
Last Resort

### ISSUE THREAD

**Issue by chaz3456** [railsbridge/docs#477]
I am in need of installation instructions, for the past three days I have been stuck on trying to update 'gem install --local rubygems-update-2.2.3.gem'. I have read all of your information, clicked on all of your links, used google, and done everything I can think of and the code will not update. I can go no further without some assistance. Any help you could provide would be greatly appreciated. Thank you

**Comment by lilliealbert** [comment]
Hi @chaz3456 — we use GitHub issues to triage the RailsBridge curriculum itself, rather than support people who are using it. You should totally ask your question on this Code Newbie thread, and a RailsBridge volunteer will help you work through it: http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594/4

**Comment by chaz3456** [comment]
Thanks
