### ISSUE TITLE
The gem version for Wrong prevents test run

### ISSUE THREAD

**Issue by danigro77** [railsbridge/docs#479]
When I try to run `rake` it does not work because a module in the Wrong gem is missing
```
/Users/dgrossmann/.rvm/gems/ruby-2.2.0@railsbridge_docs/gems/wrong-0.7.1/lib/wrong/close_to.rb:12:in `<module:Wrong>': uninitialized constant Wrong::Date (NameError)
```
Downgrading Wrong to 0.7.0 helped me, but I'm don't know the app or Sinatra well enough to make the changes with confidence in the Gemfiles myself.

**Comment by tjgrathwell** [comment]
Running `bundle exec rake` instead of `rake` always fixes this for me.

I don't know if there's anything in particular we could/should do to ensure this works outside of `bundle exec`.

**Comment by danigro77** [comment]
should we then tell this in the Contributing.md file?

**Comment by tjgrathwell** [comment]
It seems the problem with `wrong` 0.7.1 is that the `close_to` matcher references `Date` even though it may not have loaded yet. This might be fixed on `wrong`'s master branch due to [this mega-commit](https://github.com/sconover/wrong/commit/9fae5b82b3704c7bbf61b36fb9015090511742bd#diff-31dfefe855fcdf2d9cec60d95adb8039R1), but there hasn't been a new gem release with that code.

For now, I've removed `wrong` in favor of RSpec's standard `expect(this).to eq(that)` matchers.

I've also updated `CONTRIBUTING.md` and `README.md` to recommend `bundle exec`, which is generally a good idea anyway.
