### ISSUE TITLE
pushing app to Heroku

### ISSUE THREAD

**Issue by swiftcod3r** [railsbridge/docs#498]
I am able to create and set everything up yet when I try to push to Heroku I am getting an error message saying that Permission is Denied. Not sure how to get past this.

**Comment by lilliealbert** [comment]
Hi @swiftcod3r!

We use GitHub issues to triage the RailsBridge curriculum itself, rather than support people who are using it. You should totally ask your question on this Code Newbie thread, and a RailsBridge volunteer will help you work through it: http://discourse.codenewbie.org/t/railsbridge-curriculum-questions/594/4

I'm gonna close this issue, but see you there! :tada:
