### ISSUE TITLE
Linux instructions for adding SSH Key can be confusing

### ISSUE THREAD

**Issue by SteveBarnett** [railsbridge/docs#536]
We've found that [Step 4: Set up SSH authentication with GitHub](https://docs.railsbridge.org/installfest/create_a_github_account) can be confusing. Students don't understand what xclip is or why they're installing it. It might sense to take another approach since we don't use xclip anywhere else in any of the courses.

If one of the RB grown-ups :+1:s one of these ideas, I'll do a PR for it :). I like option 2 because although we're still using another new thing, it doesn't require installing anything.

Some ideas for changes:

## 1. Explain xclip

> `sudo apt-get install xclip` installs a tiny application, xclip, that lets us copy the contents of a file without opening it.

## 2. Use `cat` instead

> Linux users,
> Type this in the terminal:
> `cat ~/.ssh/id_rsa.pub`
> This shows you the contents of your SSH Key in your terminal. Highlight it and Copy it.

## 3. Move it into a text file that's easy to copy

> Linux users,
> Type this in the terminal:
> `cp ~/.ssh/id_rsa.pub ~/Desktop/ssh-key.txt`
> This copies your SSH Key to your Desktop, into a text file called ssh-key. Open that text file and copy the contents.

**Comment by lilliealbert** [comment]
I'm gonna guess that someone suggested xclip because that's what GitHub suggests:

![screen shot 2016-03-06 at 9 54 50 am](https://cloud.githubusercontent.com/assets/978428/13555909/8c80bbea-e381-11e5-955d-7937b5527d9f.png)

Probably to help people avoid adding whitespace or getting any extra stray characters in the key.

So I'd probably lean toward explaining xclip, but I don't have super strong opinions about it. (If we did use regular copy/paste, I'd probably want to echo GitHub's language about making sure not to copy any extra whitespace or newlines.)

**Comment by SteveBarnett** [comment]
Oops, butter fingers (re close and open PR). I'll add a PR with the tiny bit of explanation text above. Thanks, @lilliealbert!
