### ISSUE TITLE
Heroku Install - Do I need to install Git again? Then does it need updating?

### ISSUE THREAD

**Issue by henrythedj** [railsbridge/docs#546]
The subject says it all - the Heroku toolbelt wants to install Git.

I'm new - don't know much about all of this - but is this an extra version of Git that one needs for heroku projects?

**Comment by lilliealbert** [comment]
Hi there @henrythedj! 

We use GitHub issues to triage the RailsBridge curriculum itself, rather than support people who are using it. You should totally ask your question on our forum, though, and a RailsBridge volunteer will help you work through it! http://discourse.bridgefoundry.org/c/railsbridge-help

If it turns out something specific in the curriculum should be updated, please open a new issue! 💖
