### ISSUE TITLE
win vargant step 3 second ssh does not work

### ISSUE THREAD

**Issue by sergeborodayr** [railsbridge/docs#577]
at second  ssh it halts
Step 3: Open another Vagrant shell
http://docs.railsbridge-montreal.com/installfest/windows_vagrant

**Comment by lilliealbert** [comment]
Hi @sergeborodayr,

This is the repo for the main RailsBridge docs repo, which doesn't include Vagrant. The deployed version of this app is http://docs.railsbridge.org/installfest/. You'll probably want to get in touch with the RailsBridge Montreal chapter directly, since they are maintaining a fork of the docs.

All the best,
Lillie
