### ISSUE TITLE
with win vargant no way to access local server

### ISSUE THREAD

**Issue by sergeborodayr** [railsbridge/docs#578]
localhost:3000 would not work from the host win machine
console does not support graphic browsers
and user (me ) not sure has VM desctop, and what the credentials (to run it directly from virtualbox without vagrant)

**Comment by lilliealbert** [comment]
Hi @sergeborodayr,

This is the repo for the main RailsBridge docs repo, which doesn't include Vagrant. The deployed version of this app is http://docs.railsbridge.org/installfest/. You'll probably want to get in touch with the RailsBridge Montreal chapter directly, since they are maintaining a fork of the docs.

All the best,
Lillie
