### ISSUE TITLE
Windows terminal settings are confusing

### ISSUE THREAD

**Issue by wassimk** [railsbridge/docs#601]
On the [windows terminal command page](http://docs.railsbridge.org/installfest/configure_the_windows_terminal) we could never find the last option labeled `Modify shortcut that started this window`. I always tell students to skip the page and they will be fine. Should we remove this whole page? Perhaps I just don't understand how to do it?

**Comment by tjgrathwell** [comment]
The language is probably from some older version of windows, I don't see it on my Windows 7 PC.

I've made a change to remove that line and move that content into the [main Windows setup page](http://docs.railsbridge.org/installfest/windows#step9); it now looks like this:

![screen shot 2017-02-02 at 10 39 26 pm](https://cloud.githubusercontent.com/assets/1041691/22582145/c0dd22a6-e999-11e6-8fb0-04a1608549ab.png)

You're probably right that students are better off skipping it, because it's more trouble to explain than it is helpful, but I wasn't sure where to put all the surrounding 'tip' boxes related to "command history" and "copy paste" if the whole section went away.
